FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

COPY ModelGenerator/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ModelGenerator /app/ModelGenerator

WORKDIR /app/ModelGenerator

CMD ["python", "main.py"]