services:

  generator:
    build:
      context: .
      dockerfile: dockerfile.generator
    volumes:
      - ./DataGenerator:/app/DataGenerator       
      - ./workspace:/workspace                  
    working_dir: /app/DataGenerator
    command: ["blender", "--background", "--python", "main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  trainer:
    build:
      context: .
      dockerfile: dockerfile.model
    volumes:
      - ./ModelGenerator:/app/ModelGenerator    
      - ./workspace:/workspace                 
    working_dir: /app/ModelGenerator
    command: ["python", "main.py"]
    gpus: all